DROP DATABASE IF EXISTS toiletsandtap;
CREATE DATABASE toiletsandtap;
\c toiletsandtap;

-- ---
-- CREATE TABLES
-- ---
CREATE TABLE toiletsandtap (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id int NOT NULL,
  body text CHECK (char_length(body) <= 1000) NOT NULL,
  date_written timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  asker_name text CHECK (char_length(asker_name) <= 60) NOT NULL,
  asker_email text CHECK (char_length(asker_email) <= 60) NOT NULL,
  reported boolean NOT NULL DEFAULT false,
  helpful int NOT NULL DEFAULT 0
);


